version: '2'

services:
  mantisbt:
    image: vimagick/mantisbt:latest
    container_name: mantisbt
    ports:
      - "8989:80"
    links:
      - mysql
    restart: always

  mysql:
    image: mysql:5
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    restart: always

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - 'mariadb_data:/bitnami'
    restart: always

  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '80:80'
      - '443:443'
    links:
      - mantisbt
      - mysql
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=verysecretadminpassword
      - TESTLINK_EMAIL=admin@example.com
    restart: always

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - portainer_data:/data

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
  portainer_data:
    driver: local

#First set up mantis with the configurations below.

#           USER MANTIS
#username: administrator
#password: root
#           CONFIGS MANTIS
#Type of Database                                        MySQL/MySQLi
#Hostname (for Database Server)                          mysql
#Username (for Database)                                 mantisbt
#Password (for Database)                                 mantisbt
#Database name (for Database)                            bugtracker
#Admin Username (to create Database if required)         root
#Admin Password (to create Database if required)         root
#Print SQL Queries instead of Writing to the Database    [ ]
#Attempt Installation                                    [Install/Upgrade Database]

#           USER TESTLINK
#          username:admin
#   password:verysecretadminpassword
#           INTEGRATION TESTLINK
#<!-- Template mantissoapInterface -->
#<issuetracker>
#<username>administrator</username>
#<password>root</password>
#<uribase>http://mantisbt/</uribase>
#</issuetracker>


