version: '2.0'

services:
  mysql:
    image: mysql:5
    container_name: mysql
    networks:
    - stack
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    restart: always

  mantisbt:
    depends_on:
    - mysql
    image: vimagick/mantisbt:latest
    container_name: mantisbt
    networks:
    - stack
    ports:
      - "8989:80"
    links:
      - mysql
    restart: always
    
  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb
    networks:
    - stack
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - 'mariadb_data:/bitnami'

  testlink:
    image: 'bitnami/testlink:latest'
    container_name: testlink
    networks:
    - stack
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb
    
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=testlink
      - TESTLINK_EMAIL=admin@example.com

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local

networks: 
  stack: